### ISSUE TITLE
Response for preflight has invalid HTTP status code 403

### ISSUE THREAD

**Issue by harrisonhjones** [eddturtle/direct-upload-s3-signaturev4#1]
Hi everyone. I'm getting two errors in the Chrome console when I try running the simple example on my php server:
1. `OPTIONS http://bucket.region.amazonaws.com/` (it's "red" with little other information)
2. `XMLHttpRequest cannot load http://bucket.region.amazonaws.com/. Response for preflight has invalid HTTP status code 403` 

How do I fix this? I've got a file called `cors` in the root of my bucket with the following: 

```
<CORSConfiguration>
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>

    </CORSRule>
</CORSConfiguration>
```

Any idea what I'm missing?

Thanks!

**Comment by eddturtle** [comment]
You should add the xml in the cors configuration area.

This might help: http://blog.errorception.com/2014/11/enabling-cors-on-amazon-cloudfront-with.html

**Comment by harrisonhjones** [comment]
Thanks Edd. I looked around for the cors config and somehow completely missed the link in permissions. Works like a charm now!
