### ISSUE TITLE
Handling AWS upload response encoding quirk when uploading to folders

### ISSUE THREAD

**Issue by titpetric** [eddturtle/direct-upload-s3-signaturev4#4]
The AWS post xml response in the Location field has / encoded as %2F. It doesn't seem to be the uploader issue (things in Chrome Debug Console look like filename is sent not urlencoded).

I'm suggesting to change this line [here](https://github.com/eddturtle/direct-upload-s3-signaturev4/blob/master/index.php#L124) to include a `.replace("%2F", "/")`.

It's worth noting that the Key response comes back with a '/' and not with '%2F' as is the case with Location, so the issue is most likely with S3 and not the provided html.

**Comment by titpetric** [comment]
Full response example (redacted):

```
<PostResponse>
<Location>http://bucket.region.amazonaws.com/folder%2F1472550586248.jpg</Location>
<Bucket>bucket</Bucket>
<Key>folder/1472550586248.jpg</Key>
<ETag>"md5 string with suspicious quotes around it"</ETag>
</PostResponse>
```

**Comment by eddturtle** [comment]
Thanks for this, it seems very strange that it's passing back the url like this - especially as the key is correct. I've made the change, so it will now appear correctly.
